"""Seed data for the News Bias Platform - 5 story clusters, ~30 articles."""
from datetime import datetime, timezone, timedelta

FRAMES = {
    "economic_impact": "Economic Impact",
    "political_conflict": "Political Conflict",
    "human_interest": "Human Interest",
    "environmental": "Environmental Concern",
    "public_health": "Public Health",
    "tech_innovation": "Technological Innovation",
    "national_security": "National Security",
    "corporate_profit": "Corporate Profit",
    "social_justice": "Social Justice",
    "legal_regulatory": "Legal & Regulatory",
}

NOW = datetime.now(timezone.utc)


def _t(hours_ago: float) -> str:
    return (NOW - timedelta(hours=hours_ago)).isoformat()


STORY_CLUSTERS = [
    {
        "id": "cluster-tesla-model2",
        "event_label": "Tesla launches affordable Model 2 EV",
        "topic": "Business & Technology",
        "first_seen_at": _t(30),
        "last_updated_at": _t(2),
        "articles": [
            {
                "source": "Reuters",
                "title": "Tesla unveils Model 2, a $25,000 electric vehicle targeting mass market",
                "url": "https://reuters.com/business/autos-transportation/tesla-unveils-model-2/",
                "published_at": _t(28),
                "primary_frame": "tech_innovation",
                "sentiment_label": "neutral",
                "sentiment_score": 0.04,
                "excerpt": "Tesla Inc. on Tuesday unveiled the Model 2, a compact electric vehicle priced at $25,000, marking the company's most aggressive push into the mass-market segment. The vehicle is expected to enter production in the second half of the year.",
                "content": "Tesla Inc. on Tuesday unveiled the Model 2, a compact electric vehicle priced at $25,000, marking the company's most aggressive push into the mass-market segment. The vehicle is expected to enter production in the second half of the year at the company's Austin gigafactory. Chief Executive Elon Musk said the Model 2 will use a new manufacturing process the company calls 'unboxed assembly', which cuts production costs by nearly 50 percent compared with the Model 3. Analysts estimate initial annual production capacity at 500,000 units, ramping to 2 million by 2028. The vehicle offers an EPA-estimated range of 260 miles and Level 2 autonomy at launch.",
                "entities": [{"type": "ORG", "name": "Tesla"}, {"type": "PERSON", "name": "Elon Musk"}, {"type": "GPE", "name": "Austin"}, {"type": "MONEY", "name": "$25,000"}],
            },
            {
                "source": "Bloomberg",
                "title": "Tesla's $25,000 Model 2 raises fresh doubts over profit margins",
                "url": "https://bloomberg.com/news/articles/tesla-model-2-margins",
                "published_at": _t(26),
                "primary_frame": "corporate_profit",
                "sentiment_label": "negative",
                "sentiment_score": -0.42,
                "excerpt": "Tesla's newly announced Model 2 may struggle to deliver the margins investors have grown accustomed to, analysts warned Wednesday, sending shares lower in pre-market trading.",
                "content": "Tesla's newly announced Model 2 may struggle to deliver the margins investors have grown accustomed to, analysts warned Wednesday, sending shares lower in pre-market trading. At a $25,000 price point, gross margins on the vehicle could fall below 15 percent, well under the 25 percent floor Tesla has historically defended. Morgan Stanley called the move 'a necessary but painful' concession to intensifying competition from BYD and legacy automakers. The company has yet to disclose battery chemistry or supplier arrangements, leaving profitability projections highly uncertain. Executives face pressure to demonstrate the new unboxed assembly process can offset the aggressive pricing without eroding brand equity.",
                "entities": [{"type": "ORG", "name": "Tesla"}, {"type": "ORG", "name": "Morgan Stanley"}, {"type": "ORG", "name": "BYD"}],
            },
            {
                "source": "CNBC",
                "title": "Tesla stock surges as Model 2 reveal exceeds Wall Street expectations",
                "url": "https://cnbc.com/tesla-model-2-stock-surges",
                "published_at": _t(25),
                "primary_frame": "economic_impact",
                "sentiment_label": "positive",
                "sentiment_score": 0.62,
                "excerpt": "Tesla shares jumped as much as 8 percent Wednesday after the electric vehicle maker unveiled its long-awaited Model 2 at a price point that beat street estimates.",
                "content": "Tesla shares jumped as much as 8 percent Wednesday after the electric vehicle maker unveiled its long-awaited Model 2 at a price point that beat street estimates. The reveal drew immediate praise from bulls including Cathie Wood of Ark Invest, who reiterated her long-standing price target. Wedbush analyst Dan Ives called it 'a game-changing moment' that positions Tesla to dominate the sub-$30,000 EV segment for the next decade. Pre-orders opened within hours of the reveal, with the company reporting over 250,000 reservations in the first 12 hours. Investors cheered the aggressive production timeline and the promise of positive unit economics from day one.",
                "entities": [{"type": "ORG", "name": "Tesla"}, {"type": "PERSON", "name": "Cathie Wood"}, {"type": "ORG", "name": "Ark Invest"}, {"type": "PERSON", "name": "Dan Ives"}],
            },
            {
                "source": "The Guardian",
                "title": "Tesla's cheap EV could accelerate the end of the petrol car era",
                "url": "https://theguardian.com/environment/tesla-model-2-petrol-era",
                "published_at": _t(22),
                "primary_frame": "environmental",
                "sentiment_label": "positive",
                "sentiment_score": 0.51,
                "excerpt": "Climate campaigners have welcomed Tesla's $25,000 Model 2 as a potential tipping point in the transition away from internal combustion engines.",
                "content": "Climate campaigners have welcomed Tesla's $25,000 Model 2 as a potential tipping point in the transition away from internal combustion engines. Transport & Environment, a Brussels-based advocacy group, said the vehicle could displace millions of tonnes of CO2 annually if production targets are met. Critics of the auto industry have long argued that affordability, not luxury, is the barrier to mass EV adoption. The Model 2 arrives as governments across Europe finalize 2035 bans on new petrol car sales. Environmental groups called for stronger charging infrastructure investment to match the accelerating demand.",
                "entities": [{"type": "ORG", "name": "Tesla"}, {"type": "ORG", "name": "Transport & Environment"}, {"type": "GPE", "name": "Brussels"}, {"type": "GPE", "name": "Europe"}],
            },
            {
                "source": "BBC",
                "title": "Tesla unveils $25,000 electric car in bid to widen EV market",
                "url": "https://bbc.com/news/business/tesla-model-2-reveal",
                "published_at": _t(24),
                "primary_frame": "tech_innovation",
                "sentiment_label": "neutral",
                "sentiment_score": 0.11,
                "excerpt": "Tesla has revealed a new, more affordable electric vehicle priced at $25,000 as it faces mounting competition from Chinese rivals in the global EV market.",
                "content": "Tesla has revealed a new, more affordable electric vehicle priced at $25,000 as it faces mounting competition from Chinese rivals in the global EV market. The Model 2, unveiled at a livestreamed event, is smaller and simpler than the company's flagship Model 3. Industry analysts say the price is competitive but not disruptive, matching offerings already available in China from BYD and Geely. Production will begin at Tesla's Austin plant with plans to add capacity in Berlin and Shanghai. The company did not disclose specific delivery dates for markets outside North America.",
                "entities": [{"type": "ORG", "name": "Tesla"}, {"type": "ORG", "name": "BYD"}, {"type": "ORG", "name": "Geely"}, {"type": "GPE", "name": "Berlin"}, {"type": "GPE", "name": "Shanghai"}],
            },
            {
                "source": "Fox News",
                "title": "Tesla's cheap EV promise faces skepticism over range, dealer network",
                "url": "https://foxnews.com/tech/tesla-model-2-skepticism",
                "published_at": _t(20),
                "primary_frame": "corporate_profit",
                "sentiment_label": "negative",
                "sentiment_score": -0.28,
                "excerpt": "Tesla's newly unveiled Model 2 has drawn skepticism from consumer advocates who question whether the $25,000 price tag reflects the true cost of ownership.",
                "content": "Tesla's newly unveiled Model 2 has drawn skepticism from consumer advocates who question whether the $25,000 price tag reflects the true cost of ownership. The advertised range of 260 miles falls short of gasoline-powered competitors in the same price bracket, critics say. Tesla continues to sell direct to consumers, meaning buyers in states without a Tesla store face inconvenient service arrangements. The company has also faced repeated production delays on prior models, raising questions about whether the aggressive Model 2 timeline is realistic. Consumer Reports said it will not evaluate the vehicle until sustained deliveries begin.",
                "entities": [{"type": "ORG", "name": "Tesla"}, {"type": "ORG", "name": "Consumer Reports"}],
            },
            {
                "source": "NPR",
                "title": "How Tesla's new $25,000 car could reshape who drives electric",
                "url": "https://npr.org/tesla-affordable-ev-model-2",
                "published_at": _t(18),
                "primary_frame": "human_interest",
                "sentiment_label": "positive",
                "sentiment_score": 0.34,
                "excerpt": "For working families priced out of the electric vehicle market, Tesla's newly announced Model 2 could change the calculus of buying green.",
                "content": "For working families priced out of the electric vehicle market, Tesla's newly announced Model 2 could change the calculus of buying green. Community organizers in Detroit and Atlanta say cost has been the single biggest barrier to EV adoption in the neighborhoods they serve. At $25,000 before federal incentives, the Model 2 approaches parity with the median new-car transaction price in the United States. Advocates warn that the benefits will only reach lower-income buyers if charging access improves in rental housing and multi-family buildings. Federal programs aimed at closing the charging gap have moved slower than expected.",
                "entities": [{"type": "ORG", "name": "Tesla"}, {"type": "GPE", "name": "Detroit"}, {"type": "GPE", "name": "Atlanta"}, {"type": "GPE", "name": "United States"}],
            },
        ],
    },
    {
        "id": "cluster-fed-rates",
        "event_label": "Federal Reserve holds interest rates steady",
        "topic": "Economics & Finance",
        "first_seen_at": _t(9),
        "last_updated_at": _t(1),
        "articles": [
            {
                "source": "Reuters",
                "title": "Fed holds rates unchanged, signals patience on cuts amid sticky inflation",
                "url": "https://reuters.com/markets/us/fed-holds-rates-unchanged/",
                "published_at": _t(8),
                "primary_frame": "economic_impact",
                "sentiment_label": "neutral",
                "sentiment_score": -0.02,
                "excerpt": "The Federal Reserve on Wednesday left its benchmark interest rate unchanged for a fifth consecutive meeting, citing persistent inflation pressures.",
                "content": "The Federal Reserve on Wednesday left its benchmark interest rate unchanged for a fifth consecutive meeting, citing persistent inflation pressures that have kept core prices above the central bank's 2 percent target. Chair Jerome Powell told reporters the committee needs 'greater confidence' that inflation is moving sustainably lower before easing policy. Officials projected two rate cuts by year-end, unchanged from the March forecast. Markets had priced in a small probability of a cut at this meeting but repositioned quickly after the announcement.",
                "entities": [{"type": "ORG", "name": "Federal Reserve"}, {"type": "PERSON", "name": "Jerome Powell"}],
            },
            {
                "source": "Bloomberg",
                "title": "Powell's steady hand tests patience of markets craving relief",
                "url": "https://bloomberg.com/news/fed-powell-patience-markets",
                "published_at": _t(7),
                "primary_frame": "economic_impact",
                "sentiment_label": "negative",
                "sentiment_score": -0.31,
                "excerpt": "Jerome Powell's decision to hold rates for a fifth meeting has extended a painful waiting game for markets, rate-sensitive borrowers, and the White House.",
                "content": "Jerome Powell's decision to hold rates for a fifth meeting has extended a painful waiting game for markets, rate-sensitive borrowers, and the White House. Treasury yields climbed after the announcement, and rate-sensitive small caps sold off sharply. Housing affordability, already at a multi-decade low, looks poised to worsen through the summer selling season. Economists at Goldman Sachs pushed their first-cut forecast to September, from July. Powell's press conference offered no clear signal that the data he needs is materializing.",
                "entities": [{"type": "PERSON", "name": "Jerome Powell"}, {"type": "ORG", "name": "White House"}, {"type": "ORG", "name": "Goldman Sachs"}],
            },
            {
                "source": "CNBC",
                "title": "Fed holds rates: What it means for your mortgage, savings, and stocks",
                "url": "https://cnbc.com/fed-decision-what-it-means",
                "published_at": _t(7.5),
                "primary_frame": "human_interest",
                "sentiment_label": "neutral",
                "sentiment_score": 0.06,
                "excerpt": "The Federal Reserve's decision to keep interest rates steady has immediate consequences for consumers, from mortgage shoppers to retirees living on fixed income.",
                "content": "The Federal Reserve's decision to keep interest rates steady has immediate consequences for consumers, from mortgage shoppers to retirees living on fixed income. Mortgage rates, which loosely track the 10-year Treasury yield, are likely to stay near 7 percent for the foreseeable future. Savers, however, continue to enjoy the strongest yields on high-interest deposit accounts in more than a decade. Credit card interest rates remain at record highs, punishing carried balances. Financial planners recommend locking in current CD rates while they last.",
                "entities": [{"type": "ORG", "name": "Federal Reserve"}],
            },
            {
                "source": "BBC",
                "title": "US Federal Reserve keeps interest rates on hold amid stubborn inflation",
                "url": "https://bbc.com/news/business/us-federal-reserve-holds",
                "published_at": _t(6),
                "primary_frame": "economic_impact",
                "sentiment_label": "neutral",
                "sentiment_score": 0.02,
                "excerpt": "The US central bank has left interest rates unchanged, saying it needs more evidence that inflation is coming under control.",
                "content": "The US central bank has left interest rates unchanged, saying it needs more evidence that inflation is coming under control. The federal funds rate remains in a range of 5.25 to 5.50 percent, its highest level in more than two decades. The decision was widely expected by economists and had been priced in by financial markets. In a statement, the Fed said progress toward its 2 percent inflation goal had 'stalled' in recent months. The pound rose slightly against the dollar in London trading following the announcement.",
                "entities": [{"type": "ORG", "name": "Federal Reserve"}, {"type": "GPE", "name": "London"}],
            },
            {
                "source": "Fox News",
                "title": "Fed keeps rates high as Biden economy struggles with inflation",
                "url": "https://foxnews.com/politics/fed-rates-biden-inflation",
                "published_at": _t(6.5),
                "primary_frame": "political_conflict",
                "sentiment_label": "negative",
                "sentiment_score": -0.45,
                "excerpt": "The Federal Reserve was forced to hold interest rates at multi-decade highs Wednesday as inflation continues to plague the Biden economy.",
                "content": "The Federal Reserve was forced to hold interest rates at multi-decade highs Wednesday as inflation continues to plague the Biden economy. American families continue to struggle with soaring costs for groceries, housing, and gasoline while the White House blames external factors. Republican lawmakers criticized what they called reckless federal spending that has kept prices elevated. Chair Jerome Powell declined to comment on political questions but acknowledged the last mile of the inflation fight has proven more difficult than expected. Homebuyers remain shut out of the market.",
                "entities": [{"type": "ORG", "name": "Federal Reserve"}, {"type": "PERSON", "name": "Jerome Powell"}, {"type": "PERSON", "name": "Biden"}, {"type": "ORG", "name": "White House"}],
            },
            {
                "source": "NPR",
                "title": "The Fed pauses again — and millions of Americans keep waiting",
                "url": "https://npr.org/fed-pauses-again-waiting",
                "published_at": _t(5),
                "primary_frame": "human_interest",
                "sentiment_label": "negative",
                "sentiment_score": -0.18,
                "excerpt": "For first-time homebuyers, small-business owners, and Americans carrying credit card debt, the Federal Reserve's steady hand feels like an anvil.",
                "content": "For first-time homebuyers, small-business owners, and Americans carrying credit card debt, the Federal Reserve's steady hand feels like an anvil. In Phoenix, real-estate agent Maria Alvarez says her clients are giving up on the search. In Cleveland, small-business owner James Whitfield has postponed hiring because his line of credit costs are eating into margins. The Fed's dual mandate — stable prices and full employment — is being tested by an economy that refuses to fit into forecasters' models. Powell said the committee is 'prepared to be patient'.",
                "entities": [{"type": "ORG", "name": "Federal Reserve"}, {"type": "PERSON", "name": "Maria Alvarez"}, {"type": "GPE", "name": "Phoenix"}, {"type": "GPE", "name": "Cleveland"}, {"type": "PERSON", "name": "Jerome Powell"}],
            },
        ],
    },
    {
        "id": "cluster-climate-summit",
        "event_label": "Major climate summit reaches new emissions agreement",
        "topic": "Environment & Policy",
        "first_seen_at": _t(50),
        "last_updated_at": _t(4),
        "articles": [
            {
                "source": "The Guardian",
                "title": "Historic climate deal commits 190 nations to steep methane cuts",
                "url": "https://theguardian.com/environment/climate-summit-methane-deal",
                "published_at": _t(48),
                "primary_frame": "environmental",
                "sentiment_label": "positive",
                "sentiment_score": 0.58,
                "excerpt": "Nearly 190 nations agreed to a landmark accord requiring steep cuts in methane emissions by 2030, in what climate scientists are calling the most consequential agreement in a decade.",
                "content": "Nearly 190 nations agreed to a landmark accord requiring steep cuts in methane emissions by 2030, in what climate scientists are calling the most consequential agreement in a decade. The deal, brokered after two weeks of tense negotiations, commits signatories to a 45 percent reduction in methane emissions from 2020 levels. Environmental groups praised the outcome as the first binding agreement to target a short-lived but highly potent greenhouse gas. Small island nations, which had threatened to walk out over funding disputes, ultimately signed on after wealthy countries pledged an additional $100 billion in climate finance.",
                "entities": [{"type": "ORG", "name": "United Nations"}],
            },
            {
                "source": "Reuters",
                "title": "Climate summit concludes with methane agreement, mixed reactions on financing",
                "url": "https://reuters.com/business/environment/climate-summit-concludes",
                "published_at": _t(47),
                "primary_frame": "legal_regulatory",
                "sentiment_label": "neutral",
                "sentiment_score": 0.09,
                "excerpt": "A two-week climate summit ended Sunday with a formal agreement on methane reductions, though delegates from developing nations expressed disappointment with the final financing terms.",
                "content": "A two-week climate summit ended Sunday with a formal agreement on methane reductions, though delegates from developing nations expressed disappointment with the final financing terms. The accord requires participating countries to submit national action plans within 18 months. Verification mechanisms will rely on satellite monitoring operated by a consortium of research institutions. Enforcement remains voluntary, a compromise that drew criticism from environmental NGOs but was necessary to secure buy-in from major fossil-fuel producing states. Follow-up negotiations are scheduled for next year.",
                "entities": [{"type": "ORG", "name": "United Nations"}],
            },
            {
                "source": "Al Jazeera",
                "title": "Climate deal welcomed, but Global South says financing falls far short",
                "url": "https://aljazeera.com/news/climate-summit-global-south",
                "published_at": _t(46),
                "primary_frame": "social_justice",
                "sentiment_label": "negative",
                "sentiment_score": -0.14,
                "excerpt": "Delegates from developing nations welcomed the methane agreement but sharply criticized the level of climate financing offered by wealthy countries.",
                "content": "Delegates from developing nations welcomed the methane agreement but sharply criticized the level of climate financing offered by wealthy countries. The $100 billion pledge, they said, is inadequate compared with the $1 trillion annually that experts estimate will be needed by 2030. Representatives from the African Group and the Alliance of Small Island States said they had been pressured into accepting the deal despite its shortcomings. Historical emitters, they argued, continue to shift the burden of the transition onto vulnerable nations. Activists staged demonstrations outside the venue.",
                "entities": [{"type": "ORG", "name": "African Group"}, {"type": "ORG", "name": "Alliance of Small Island States"}],
            },
            {
                "source": "BBC",
                "title": "COP delegates strike deal on methane after marathon talks",
                "url": "https://bbc.com/news/climate-cop-methane-deal",
                "published_at": _t(48.5),
                "primary_frame": "environmental",
                "sentiment_label": "neutral",
                "sentiment_score": 0.15,
                "excerpt": "After more than 36 hours of continuous negotiation, delegates at the international climate summit have reached agreement on binding methane targets.",
                "content": "After more than 36 hours of continuous negotiation, delegates at the international climate summit have reached agreement on binding methane targets. The final text was gaveled through in the early hours of Sunday morning to loud applause from environmental observers. Britain, the United States, and the European Union led the push for a binding target, while several major oil producers had sought a voluntary framework. The agreement includes provisions for technology transfer to help lower-income countries meet the targets. Details on verification and non-compliance procedures will be finalized at follow-up meetings.",
                "entities": [{"type": "GPE", "name": "Britain"}, {"type": "GPE", "name": "United States"}, {"type": "ORG", "name": "European Union"}],
            },
            {
                "source": "Fox News",
                "title": "US signs onto sweeping climate deal, critics warn of economic cost",
                "url": "https://foxnews.com/politics/us-climate-deal-cost",
                "published_at": _t(45),
                "primary_frame": "economic_impact",
                "sentiment_label": "negative",
                "sentiment_score": -0.37,
                "excerpt": "The United States has committed to a sweeping international methane agreement, drawing sharp criticism from industry groups and lawmakers who warn of significant economic costs.",
                "content": "The United States has committed to a sweeping international methane agreement, drawing sharp criticism from industry groups and lawmakers who warn of significant economic costs. The American Petroleum Institute said the timelines are unrealistic and could accelerate domestic energy production offshore. Republican lawmakers called the commitment an overreach that bypasses congressional authority. The administration defended the deal as consistent with existing regulatory action under the Clean Air Act. Energy sector shares fell modestly in Monday trading.",
                "entities": [{"type": "GPE", "name": "United States"}, {"type": "ORG", "name": "American Petroleum Institute"}],
            },
            {
                "source": "NPR",
                "title": "'A first step': Scientists cautiously welcome global methane pact",
                "url": "https://npr.org/climate-methane-pact-scientists",
                "published_at": _t(44),
                "primary_frame": "environmental",
                "sentiment_label": "positive",
                "sentiment_score": 0.42,
                "excerpt": "Climate scientists are cautiously welcoming the new international agreement on methane emissions, calling it a meaningful but insufficient step forward.",
                "content": "Climate scientists are cautiously welcoming the new international agreement on methane emissions, calling it a meaningful but insufficient step forward. Methane is roughly 80 times more potent than carbon dioxide over a 20-year period, meaning aggressive near-term cuts can slow warming quickly. Researchers at Stanford and Oxford say the 45 percent target is achievable with existing technology. The pact does not address agricultural methane emissions, which represent a growing share of the total. Follow-up commitments on agriculture, waste, and coal mine methane are expected within two years.",
                "entities": [{"type": "ORG", "name": "Stanford"}, {"type": "ORG", "name": "Oxford"}],
            },
            {
                "source": "The Hindu",
                "title": "India signs climate methane pact, seeks larger role in technology transfer",
                "url": "https://thehindu.com/news/international/india-methane-pact",
                "published_at": _t(43),
                "primary_frame": "legal_regulatory",
                "sentiment_label": "neutral",
                "sentiment_score": 0.08,
                "excerpt": "India has joined the international methane agreement while pressing for a larger role in the technology-transfer mechanisms embedded in the accord.",
                "content": "India has joined the international methane agreement while pressing for a larger role in the technology-transfer mechanisms embedded in the accord. Environment Minister Bhupender Yadav said India will need financial and technical support to meet the agriculture-related components of the deal. Rice paddies, livestock, and landfill sites are the largest domestic sources of methane. The government also called for updated verification standards that reflect the realities of monsoon-affected regions. Development economists said the deal creates an opportunity to modernize agricultural practices at scale.",
                "entities": [{"type": "GPE", "name": "India"}, {"type": "PERSON", "name": "Bhupender Yadav"}],
            },
            {
                "source": "Bloomberg",
                "title": "Global methane deal opens $200 billion market for leak-detection tech",
                "url": "https://bloomberg.com/news/climate-methane-leak-detection",
                "published_at": _t(42),
                "primary_frame": "corporate_profit",
                "sentiment_label": "positive",
                "sentiment_score": 0.36,
                "excerpt": "The international methane agreement announced this weekend is expected to unlock more than $200 billion of investment in leak-detection and abatement technology.",
                "content": "The international methane agreement announced this weekend is expected to unlock more than $200 billion of investment in leak-detection and abatement technology over the next decade. Satellite-imagery firms, industrial sensor makers, and oilfield-services companies are all positioning to capture a share of the new spending. Analysts identified a dozen publicly traded companies most likely to benefit. Governments have signalled that compliance grants will be tied to procurement of verifiable technology solutions. Venture-backed startups in Houston, Amsterdam, and Bengaluru have already reported spikes in inquiries.",
                "entities": [{"type": "GPE", "name": "Houston"}, {"type": "GPE", "name": "Amsterdam"}, {"type": "GPE", "name": "Bengaluru"}],
            },
        ],
    },
    {
        "id": "cluster-ai-regulation",
        "event_label": "New AI regulation bill introduced in Congress",
        "topic": "Technology & Policy",
        "first_seen_at": _t(20),
        "last_updated_at": _t(3),
        "articles": [
            {
                "source": "Reuters",
                "title": "Bipartisan bill would require federal licensing for advanced AI models",
                "url": "https://reuters.com/technology/us-ai-regulation-bill",
                "published_at": _t(19),
                "primary_frame": "legal_regulatory",
                "sentiment_label": "neutral",
                "sentiment_score": 0.05,
                "excerpt": "A bipartisan group of US senators introduced legislation Tuesday that would require federal licensing for the most advanced AI systems.",
                "content": "A bipartisan group of US senators introduced legislation Tuesday that would require federal licensing for the most advanced AI systems, marking the most significant congressional push to regulate the technology to date. The bill would establish a new oversight body within the Commerce Department empowered to audit frontier models before they are released. Companies developing systems exceeding a specified computational threshold would be required to submit safety evaluations and register with the new regulator. Industry reaction was mixed. The bill faces a difficult path through committee amid a crowded legislative calendar.",
                "entities": [{"type": "ORG", "name": "Congress"}, {"type": "ORG", "name": "Commerce Department"}],
            },
            {
                "source": "CNBC",
                "title": "AI bill threatens Silicon Valley's laissez-faire era, tech leaders warn",
                "url": "https://cnbc.com/tech/ai-bill-silicon-valley",
                "published_at": _t(17),
                "primary_frame": "corporate_profit",
                "sentiment_label": "negative",
                "sentiment_score": -0.36,
                "excerpt": "Silicon Valley leaders are warning that the newly introduced AI licensing bill could stifle innovation and hand a competitive edge to Chinese rivals.",
                "content": "Silicon Valley leaders are warning that the newly introduced AI licensing bill could stifle innovation and hand a competitive edge to Chinese rivals. Executives at leading AI labs said the licensing regime would add months to development cycles and impose compliance costs that only the largest firms could absorb. Venture-capital investors expressed concern that the bill would freeze early-stage funding in the sector. The trade group NetChoice said the measure amounts to a 'permission slip' requirement for building software. Supporters counter that the threshold is calibrated to affect only a handful of well-resourced developers.",
                "entities": [{"type": "GPE", "name": "Silicon Valley"}, {"type": "ORG", "name": "NetChoice"}],
            },
            {
                "source": "BBC",
                "title": "US lawmakers unveil sweeping AI oversight bill",
                "url": "https://bbc.com/news/technology/us-ai-oversight-bill",
                "published_at": _t(18),
                "primary_frame": "legal_regulatory",
                "sentiment_label": "neutral",
                "sentiment_score": 0.12,
                "excerpt": "US lawmakers have introduced a wide-ranging bill that would create federal oversight of the most powerful artificial intelligence systems.",
                "content": "US lawmakers have introduced a wide-ranging bill that would create federal oversight of the most powerful artificial intelligence systems. The measure follows more than a year of hearings and study by a bipartisan working group. It would require pre-deployment safety testing, incident reporting, and public disclosures of training data provenance. The UK and EU have both moved ahead of the US on AI regulation, and the bill's authors said the legislation aims to close the gap. The White House expressed general support but stopped short of endorsing specific provisions.",
                "entities": [{"type": "GPE", "name": "United States"}, {"type": "GPE", "name": "UK"}, {"type": "ORG", "name": "European Union"}, {"type": "ORG", "name": "White House"}],
            },
            {
                "source": "NPR",
                "title": "Behind the AI bill: The workers and researchers who spent years pushing for it",
                "url": "https://npr.org/ai-regulation-bill-workers",
                "published_at": _t(15),
                "primary_frame": "human_interest",
                "sentiment_label": "positive",
                "sentiment_score": 0.29,
                "excerpt": "The AI oversight bill introduced this week reflects years of work by researchers, whistleblowers, and workers whose jobs have been disrupted by the technology.",
                "content": "The AI oversight bill introduced this week reflects years of work by researchers, whistleblowers, and workers whose jobs have been disrupted by the technology. Members of the Writers Guild, the SAG-AFTRA union, and displaced call-center workers testified in Senate hearings that shaped the bill's disclosure provisions. Former employees of leading AI labs called for mandatory safety testing after describing internal pressures to ship models quickly. Advocates said the introduction of the bill represents 'a rare moment' when public concerns broke through the industry's lobbying power.",
                "entities": [{"type": "ORG", "name": "Writers Guild"}, {"type": "ORG", "name": "SAG-AFTRA"}],
            },
            {
                "source": "Fox News",
                "title": "New AI bill sparks free-speech concerns, GOP lawmakers push back",
                "url": "https://foxnews.com/politics/ai-bill-free-speech-concerns",
                "published_at": _t(16),
                "primary_frame": "political_conflict",
                "sentiment_label": "negative",
                "sentiment_score": -0.24,
                "excerpt": "Republican lawmakers are pushing back against portions of the newly introduced AI bill, warning that broad content-safety provisions could enable government censorship.",
                "content": "Republican lawmakers are pushing back against portions of the newly introduced AI bill, warning that broad content-safety provisions could enable government censorship. Critics said the bill's authority for the regulator to demand training-data disclosures could be weaponized against models that produce disfavored viewpoints. Conservative legal scholars argued the licensing regime raises First Amendment issues. Supporters of the bill dismissed the concerns as premature and said the enforcement mechanisms are narrowly scoped. A markup in the relevant committee is scheduled for next month.",
                "entities": [{"type": "ORG", "name": "Congress"}],
            },
        ],
    },
    {
        "id": "cluster-semiconductor",
        "event_label": "Global semiconductor shortage eases",
        "topic": "Business & Supply Chain",
        "first_seen_at": _t(15),
        "last_updated_at": _t(2),
        "articles": [
            {
                "source": "Bloomberg",
                "title": "Chip shortage fades as inventories return to pre-pandemic norms",
                "url": "https://bloomberg.com/news/chip-shortage-inventory-normalizes",
                "published_at": _t(14),
                "primary_frame": "corporate_profit",
                "sentiment_label": "positive",
                "sentiment_score": 0.43,
                "excerpt": "The global semiconductor shortage that hobbled manufacturers across industries has receded, with inventories at automakers and consumer electronics firms returning to pre-pandemic norms.",
                "content": "The global semiconductor shortage that hobbled manufacturers across industries has receded, with inventories at automakers and consumer electronics firms returning to pre-pandemic norms. Bloomberg's index of lead times fell to 12 weeks in the latest reading, matching 2019 averages. Companies including General Motors, Ford, and Sony have announced production increases citing improved chip availability. Analysts at Bernstein said the industry is now closer to oversupply than shortage in mature nodes. Investor attention is shifting to whether pricing power at foundries can be sustained through the next cycle.",
                "entities": [{"type": "ORG", "name": "General Motors"}, {"type": "ORG", "name": "Ford"}, {"type": "ORG", "name": "Sony"}, {"type": "ORG", "name": "Bernstein"}],
            },
            {
                "source": "Reuters",
                "title": "Semiconductor supply improves, but geopolitical risks linger",
                "url": "https://reuters.com/technology/semiconductor-supply-improves",
                "published_at": _t(13),
                "primary_frame": "national_security",
                "sentiment_label": "neutral",
                "sentiment_score": 0.02,
                "excerpt": "Semiconductor availability has improved sharply over the past six months, though the industry remains exposed to concentrated geopolitical risks.",
                "content": "Semiconductor availability has improved sharply over the past six months, though the industry remains exposed to concentrated geopolitical risks. More than 90 percent of the world's advanced-node chip capacity remains in Taiwan and South Korea. US export controls on advanced chipmaking equipment have created uncertainty for planned expansions in mainland China. The CHIPS Act has begun disbursing subsidies to fabricators building capacity in Arizona, Ohio, and Texas, but production timelines stretch into 2026 and beyond. Industry executives urged policymakers to preserve open trade channels for legacy nodes.",
                "entities": [{"type": "GPE", "name": "Taiwan"}, {"type": "GPE", "name": "South Korea"}, {"type": "GPE", "name": "Arizona"}, {"type": "GPE", "name": "Ohio"}, {"type": "GPE", "name": "Texas"}],
            },
            {
                "source": "CNBC",
                "title": "The chip drought is over — here's what it means for tech stocks",
                "url": "https://cnbc.com/chip-drought-over-tech-stocks",
                "published_at": _t(11),
                "primary_frame": "economic_impact",
                "sentiment_label": "positive",
                "sentiment_score": 0.51,
                "excerpt": "With the global chip shortage now firmly behind us, investors are rotating into semiconductor equipment makers and cyclicals leveraged to consumer electronics demand.",
                "content": "With the global chip shortage now firmly behind us, investors are rotating into semiconductor equipment makers and cyclicals leveraged to consumer electronics demand. ASML, Applied Materials, and Lam Research have each gained more than 20 percent over the past quarter. Consumer electronics names are also outperforming as pricing pressure eases and inventory clearances complete. Analysts at Morgan Stanley expect a broad-based recovery in PC and smartphone shipments through the second half. Risks include a slowdown in AI-chip demand and continued weakness in industrial end markets.",
                "entities": [{"type": "ORG", "name": "ASML"}, {"type": "ORG", "name": "Applied Materials"}, {"type": "ORG", "name": "Lam Research"}, {"type": "ORG", "name": "Morgan Stanley"}],
            },
            {
                "source": "The Hindu",
                "title": "Indian electronics manufacturers welcome easing of global chip crunch",
                "url": "https://thehindu.com/business/india-electronics-chip-crunch",
                "published_at": _t(10),
                "primary_frame": "economic_impact",
                "sentiment_label": "positive",
                "sentiment_score": 0.38,
                "excerpt": "Indian electronics manufacturers are welcoming the easing global semiconductor shortage, which has held back production plans across consumer devices and automotive assembly.",
                "content": "Indian electronics manufacturers are welcoming the easing global semiconductor shortage, which has held back production plans across consumer devices and automotive assembly. Domestic assembly of smartphones, home appliances, and passenger vehicles was constrained through much of the past two years. The government's production-linked incentive scheme has drawn commitments from Micron and Foxconn to build local packaging and assembly facilities. Industry groups called for a similar push into fabrication, which remains dominated by East Asian producers. Consumers can expect improved product availability heading into the festive season.",
                "entities": [{"type": "GPE", "name": "India"}, {"type": "ORG", "name": "Micron"}, {"type": "ORG", "name": "Foxconn"}],
            },
        ],
    },
]


def get_seed_articles_and_clusters():
    """Flatten seed data into cluster docs and article docs ready for MongoDB insertion."""
    clusters = []
    articles = []
    for cluster in STORY_CLUSTERS:
        # Compute cluster aggregates
        sentiments = [a["sentiment_score"] for a in cluster["articles"]]
        avg_sentiment = sum(sentiments) / len(sentiments)
        frame_counts = {}
        for a in cluster["articles"]:
            frame_counts[a["primary_frame"]] = frame_counts.get(a["primary_frame"], 0) + 1
        most_common = max(frame_counts.values())
        frame_diversity = round(1 - (most_common / len(cluster["articles"])), 2)
        # Aggregate entities
        entity_map = {}
        for a in cluster["articles"]:
            for e in a.get("entities", []):
                key = (e["type"], e["name"])
                entity_map[key] = entity_map.get(key, 0) + 1
        common_entities = [
            {"type": t, "name": n, "mentions": c}
            for (t, n), c in sorted(entity_map.items(), key=lambda x: -x[1])
        ]
        cluster_doc = {
            "id": cluster["id"],
            "event_label": cluster["event_label"],
            "topic": cluster["topic"],
            "first_seen_at": cluster["first_seen_at"],
            "last_updated_at": cluster["last_updated_at"],
            "article_count": len(cluster["articles"]),
            "publisher_list": sorted({a["source"] for a in cluster["articles"]}),
            "avg_sentiment": round(avg_sentiment, 3),
            "frame_diversity_score": frame_diversity,
            "primary_frames": sorted(frame_counts.items(), key=lambda x: -x[1])[:3],
            "common_entities": common_entities,
            "neutral_summary": None,  # generated on first fetch
        }
        clusters.append(cluster_doc)
        for idx, art in enumerate(cluster["articles"]):
            article_doc = {
                "id": f"{cluster['id']}-art-{idx}",
                "cluster_id": cluster["id"],
                **art,
            }
            articles.append(article_doc)
    return clusters, articles
