import { Radar, Layers, Sparkles, Users } from "lucide-react";

const steps = [
  { icon: Layers, title: "1. Ingest", body: "We continuously pull articles from major publishers — Reuters, BBC, Bloomberg, CNBC, Guardian, NPR, Fox News, Al Jazeera, The Hindu and more — covering the same real-world events." },
  { icon: Radar, title: "2. Cluster", body: "An embedding model groups articles that describe the same event, no matter how differently they are titled or framed." },
  { icon: Sparkles, title: "3. Analyze", body: "For every article we score sentiment (VADER), detect editorial framing (LLM zero-shot), extract named entities and identify shared facts." },
  { icon: Users, title: "4. Synthesize", body: "A neutral cross-article summary is generated by Claude Sonnet from up to eight publisher accounts — verifiable facts only, no editorial stance." },
];

export default function About() {
  return (
    <div className="max-w-4xl mx-auto px-6 lg:px-10 py-14">
      <div className="overline mb-3">About PRISM</div>
      <h1 className="font-display text-4xl lg:text-5xl font-bold text-slate-50 tracking-tight mb-6 leading-tight">
        A terminal for reading between the sources.
      </h1>
      <p className="text-slate-400 text-lg leading-relaxed mb-14 max-w-2xl">
        PRISM is a media-literacy tool. It doesn&rsquo;t tell you what to think — it shows you how the same event is
        being told by different newsrooms, and lets you decide what matters.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-16">
        {steps.map((s, i) => (
          <div key={i} className="border border-slate-800 bg-slate-950 p-6">
            <s.icon className="w-4 h-4 text-emerald-400 mb-4" strokeWidth={1.5} />
            <div className="font-display text-lg font-semibold text-slate-100 tracking-tight mb-2">{s.title}</div>
            <p className="text-slate-400 text-sm leading-relaxed">{s.body}</p>
          </div>
        ))}
      </div>

      <div className="border-l-2 border-emerald-500/40 pl-5 py-1 mb-10">
        <p className="text-slate-300 leading-relaxed">
          &ldquo;The point is not to distrust every source, but to notice which parts of a story each source chooses to
          amplify — and which parts they leave on the cutting room floor.&rdquo;
        </p>
      </div>

      <div className="border border-slate-800 bg-slate-950 p-6">
        <div className="overline mb-3">Phase 2 roadmap</div>
        <ul className="space-y-2 text-sm text-slate-400 font-mono">
          <li>· Live RSS ingestion every 60 minutes</li>
          <li>· Side-by-side four-way article compare with diff highlighting</li>
          <li>· Publisher bias profiles (30-day sentiment trend, frame usage)</li>
          <li>· Publication timeline scatter (who broke the story first)</li>
          <li>· Trending entities sidebar and entity drill-down pages</li>
        </ul>
      </div>
    </div>
  );
}
